service:
  name: hello-world

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: development
  region: eu-west-1
  includeModules: false

package:
  individually: true

functions:
  hello-world:
    handler: lib/index.handle
